// memory_master.xlsx から自動生成したファイルです。
// このファイルは直接編集せず、Excelを編集してください。

const MEMORY_CARDS = {
  "あの日の_夏祭り": {
    "no": "001",
    "memoryId": "M001",
    "word1": "あの日の",
    "word2": "夏祭り",
    "title": "あの日の夏祭り",
    "poem": "月が低く見えた。\nあの日の夏祭りを思い出しそうになる。\n夜風だけ覚えていた。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:あの日の夏祭り. Mood:月が低く見えた。\nあの日の夏祭りを思い出しそうになる。\n夜風だけ覚えていた。",
    "image": "images/memory/001.webp",
    "status": "pending"
  },
  "あの日の_花火": {
    "no": "002",
    "memoryId": "M002",
    "word1": "あの日の",
    "word2": "花火",
    "title": "あの日の花火",
    "poem": "月が低く見えた。\n線香花火をまだ信じていた。\n光だけ笑っていた。",
    "mood": "Smile",
    "composition": "後ろ姿",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:あの日の花火. Mood:月が低く見えた。\n線香花火をまだ信じていた。\n光だけ笑っていた。",
    "image": "images/memory/002.webp",
    "status": "pending"
  },
  "あの日の_ラムネ": {
    "no": "003",
    "memoryId": "M003",
    "word1": "あの日の",
    "word2": "ラムネ",
    "title": "あの日のラムネ",
    "poem": "汗が少し乾いた。\nあの日のラムネを思い出しそうになる。\nビー玉だけ帰らなかった。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:あの日のラムネ. Mood:汗が少し乾いた。\nあの日のラムネを思い出しそうになる。\nビー玉だけ帰らなかった。",
    "image": "images/memory/003.webp",
    "status": "pending"
  },
  "あの日の_夕暮れ": {
    "no": "004",
    "memoryId": "M004",
    "word1": "あの日の",
    "word2": "夕暮れ",
    "title": "あの日の夕暮れ",
    "poem": "空はまだ青かった。\nビー玉が最後まで出てこない。\n風だけ知っていた。",
    "mood": "Smile",
    "composition": "後ろ姿",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:あの日の夕暮れ. Mood:空はまだ青かった。\nビー玉が最後まで出てこない。\n風だけ知っていた。",
    "image": "images/memory/004.webp",
    "status": "pending"
  },
  "あの日の_鳥居": {
    "no": "005",
    "memoryId": "M005",
    "word1": "あの日の",
    "word2": "鳥居",
    "title": "あの日の鳥居",
    "poem": "汗が少し乾いた。\nあの日の鳥居を思い出しそうになる。\n境界だけ揺れていた。",
    "mood": "Serious",
    "composition": "手元",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:あの日の鳥居. Mood:汗が少し乾いた。\nあの日の鳥居を思い出しそうになる。\n境界だけ揺れていた。",
    "image": "images/memory/005.webp",
    "status": "pending"
  },
  "あの日の_灯籠": {
    "no": "006",
    "memoryId": "M006",
    "word1": "あの日の",
    "word2": "灯籠",
    "title": "あの日の灯籠",
    "poem": "汗が少し乾いた。\nラムネの泡だけ元気だった。\n灯りだけ残っていた。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:あの日の灯籠. Mood:汗が少し乾いた。\nラムネの泡だけ元気だった。\n灯りだけ残っていた。",
    "image": "images/memory/006.webp",
    "status": "pending"
  },
  "あの日の_河川敷": {
    "no": "007",
    "memoryId": "M007",
    "word1": "あの日の",
    "word2": "河川敷",
    "title": "あの日の河川敷",
    "poem": "風が少し止んだ。\nあの日の河川敷を思い出しそうになる。\n風だけ遊んでいた。",
    "mood": "Serious",
    "composition": "横顔",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:あの日の河川敷. Mood:風が少し止んだ。\nあの日の河川敷を思い出しそうになる。\n風だけ遊んでいた。",
    "image": "images/memory/007.webp",
    "status": "pending"
  },
  "あの日の_蝉時雨": {
    "no": "008",
    "memoryId": "M008",
    "word1": "あの日の",
    "word2": "蝉時雨",
    "title": "あの日の蝉時雨",
    "poem": "ノイズが静かに混ざる。\nビー玉が最後まで出てこない。\n音だけ夏だった。",
    "mood": "Smile",
    "composition": "横顔",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:あの日の蝉時雨. Mood:ノイズが静かに混ざる。\nビー玉が最後まで出てこない。\n音だけ夏だった。",
    "image": "images/memory/008.webp",
    "status": "pending"
  },
  "あの日の_祭り囃子": {
    "no": "009",
    "memoryId": "M009",
    "word1": "あの日の",
    "word2": "祭り囃子",
    "title": "あの日の祭り囃子",
    "poem": "夜気がゆっくり近づく。\nあの日の祭り囃子を思い出しそうになる。\n音だけ帰らなかった。",
    "mood": "Serious",
    "composition": "足元",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:あの日の祭り囃子. Mood:夜気がゆっくり近づく。\nあの日の祭り囃子を思い出しそうになる。\n音だけ帰らなかった。",
    "image": "images/memory/009.webp",
    "status": "pending"
  },
  "あの日の_帰り道": {
    "no": "010",
    "memoryId": "M010",
    "word1": "あの日の",
    "word2": "帰り道",
    "title": "あの日の帰り道",
    "poem": "汗が少し乾いた。\n扇風機に向かって『あー』と言いたくなった。\n靴音だけ続いていた。",
    "mood": "Smile",
    "composition": "後ろ姿",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:あの日の帰り道. Mood:汗が少し乾いた。\n扇風機に向かって『あー』と言いたくなった。\n靴音だけ続いていた。",
    "image": "images/memory/010.webp",
    "status": "pending"
  },
  "あの日の_夜店": {
    "no": "011",
    "memoryId": "M011",
    "word1": "あの日の",
    "word2": "夜店",
    "title": "あの日の夜店",
    "poem": "ノイズが静かに混ざる。\nあの日の夜店を思い出しそうになる。\nお腹だけ急いでいた。",
    "mood": "Serious",
    "composition": "横顔",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:あの日の夜店. Mood:ノイズが静かに混ざる。\nあの日の夜店を思い出しそうになる。\nお腹だけ急いでいた。",
    "image": "images/memory/011.webp",
    "status": "pending"
  },
  "あの日の_打ち上げ跡": {
    "no": "012",
    "memoryId": "M012",
    "word1": "あの日の",
    "word2": "打ち上げ跡",
    "title": "あの日の打ち上げ跡",
    "poem": "風鈴がひとつ鳴った。\nラムネの泡だけ元気だった。\n静けさだけ広がった。",
    "mood": "Smile",
    "composition": "横顔",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:あの日の打ち上げ跡. Mood:風鈴がひとつ鳴った。\nラムネの泡だけ元気だった。\n静けさだけ広がった。",
    "image": "images/memory/012.webp",
    "status": "pending"
  },
  "最後の_夏祭り": {
    "no": "013",
    "memoryId": "M013",
    "word1": "最後の",
    "word2": "夏祭り",
    "title": "最後の夏祭り",
    "poem": "夜気がゆっくり近づく。\n最後の夏祭りを思い出しそうになる。\n提灯だけが揺れていた。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:最後の夏祭り. Mood:夜気がゆっくり近づく。\n最後の夏祭りを思い出しそうになる。\n提灯だけが揺れていた。",
    "image": "images/memory/013.webp",
    "status": "pending"
  },
  "最後の_花火": {
    "no": "014",
    "memoryId": "M014",
    "word1": "最後の",
    "word2": "花火",
    "title": "最後の花火",
    "poem": "夜気がゆっくり近づく。\nラムネの泡だけ元気だった。\n空だけ覚えていた。",
    "mood": "Smile",
    "composition": "鳥居",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:最後の花火. Mood:夜気がゆっくり近づく。\nラムネの泡だけ元気だった。\n空だけ覚えていた。",
    "image": "images/memory/014.webp",
    "status": "pending"
  },
  "最後の_ラムネ": {
    "no": "015",
    "memoryId": "M015",
    "word1": "最後の",
    "word2": "ラムネ",
    "title": "最後のラムネ",
    "poem": "ノイズが静かに混ざる。\n最後のラムネを思い出しそうになる。\n指だけ頑張っていた。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:最後のラムネ. Mood:ノイズが静かに混ざる。\n最後のラムネを思い出しそうになる。\n指だけ頑張っていた。",
    "image": "images/memory/015.webp",
    "status": "pending"
  },
  "最後の_夕暮れ": {
    "no": "016",
    "memoryId": "M016",
    "word1": "最後の",
    "word2": "夕暮れ",
    "title": "最後の夕暮れ",
    "poem": "風鈴がひとつ鳴った。\nビー玉が最後まで出てこない。\n影だけ伸びていた。",
    "mood": "Smile",
    "composition": "後ろ姿",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:最後の夕暮れ. Mood:風鈴がひとつ鳴った。\nビー玉が最後まで出てこない。\n影だけ伸びていた。",
    "image": "images/memory/016.webp",
    "status": "pending"
  },
  "最後の_鳥居": {
    "no": "017",
    "memoryId": "M017",
    "word1": "最後の",
    "word2": "鳥居",
    "title": "最後の鳥居",
    "poem": "夜気がゆっくり近づく。\n最後の鳥居を思い出しそうになる。\n境界だけ揺れていた。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:最後の鳥居. Mood:夜気がゆっくり近づく。\n最後の鳥居を思い出しそうになる。\n境界だけ揺れていた。",
    "image": "images/memory/017.webp",
    "status": "pending"
  },
  "最後の_灯籠": {
    "no": "018",
    "memoryId": "M018",
    "word1": "最後の",
    "word2": "灯籠",
    "title": "最後の灯籠",
    "poem": "風鈴がひとつ鳴った。\n扇風機に向かって『あー』と言いたくなった。\n光だけ流れていた。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:最後の灯籠. Mood:風鈴がひとつ鳴った。\n扇風機に向かって『あー』と言いたくなった。\n光だけ流れていた。",
    "image": "images/memory/018.webp",
    "status": "pending"
  },
  "最後の_河川敷": {
    "no": "019",
    "memoryId": "M019",
    "word1": "最後の",
    "word2": "河川敷",
    "title": "最後の河川敷",
    "poem": "灯りが水面にほどける。\n最後の河川敷を思い出しそうになる。\n水面だけ笑っていた。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:最後の河川敷. Mood:灯りが水面にほどける。\n最後の河川敷を思い出しそうになる。\n水面だけ笑っていた。",
    "image": "images/memory/019.webp",
    "status": "pending"
  },
  "最後の_蝉時雨": {
    "no": "020",
    "memoryId": "M020",
    "word1": "最後の",
    "word2": "蝉時雨",
    "title": "最後の蝉時雨",
    "poem": "ノイズが静かに混ざる。\n屋台の匂いに負けた。\n音だけ夏だった。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:最後の蝉時雨. Mood:ノイズが静かに混ざる。\n屋台の匂いに負けた。\n音だけ夏だった。",
    "image": "images/memory/020.webp",
    "status": "pending"
  },
  "最後の_祭り囃子": {
    "no": "021",
    "memoryId": "M021",
    "word1": "最後の",
    "word2": "祭り囃子",
    "title": "最後の祭り囃子",
    "poem": "月が低く見えた。\n最後の祭り囃子を思い出しそうになる。\n夜だけ踊っていた。",
    "mood": "Serious",
    "composition": "鳥居",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:最後の祭り囃子. Mood:月が低く見えた。\n最後の祭り囃子を思い出しそうになる。\n夜だけ踊っていた。",
    "image": "images/memory/021.webp",
    "status": "pending"
  },
  "最後の_帰り道": {
    "no": "022",
    "memoryId": "M022",
    "word1": "最後の",
    "word2": "帰り道",
    "title": "最後の帰り道",
    "poem": "灯りが水面にほどける。\n屋台の匂いに負けた。\n街灯だけ待っていた。",
    "mood": "Smile",
    "composition": "横顔",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:最後の帰り道. Mood:灯りが水面にほどける。\n屋台の匂いに負けた。\n街灯だけ待っていた。",
    "image": "images/memory/022.webp",
    "status": "pending"
  },
  "最後の_夜店": {
    "no": "023",
    "memoryId": "M023",
    "word1": "最後の",
    "word2": "夜店",
    "title": "最後の夜店",
    "poem": "夜気がゆっくり近づく。\n最後の夜店を思い出しそうになる。\n財布だけ静かだった。",
    "mood": "Serious",
    "composition": "手元",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:最後の夜店. Mood:夜気がゆっくり近づく。\n最後の夜店を思い出しそうになる。\n財布だけ静かだった。",
    "image": "images/memory/023.webp",
    "status": "pending"
  },
  "最後の_打ち上げ跡": {
    "no": "024",
    "memoryId": "M024",
    "word1": "最後の",
    "word2": "打ち上げ跡",
    "title": "最後の打ち上げ跡",
    "poem": "夜気がゆっくり近づく。\n線香花火をまだ信じていた。\n煙だけ知っていた。",
    "mood": "Smile",
    "composition": "横顔",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:最後の打ち上げ跡. Mood:夜気がゆっくり近づく。\n線香花火をまだ信じていた。\n煙だけ知っていた。",
    "image": "images/memory/024.webp",
    "status": "pending"
  },
  "夏の_夏祭り": {
    "no": "025",
    "memoryId": "M025",
    "word1": "夏の",
    "word2": "夏祭り",
    "title": "夏の夏祭り",
    "poem": "ノイズが静かに混ざる。\n夏の夏祭りを思い出しそうになる。\n夜風だけ覚えていた。",
    "mood": "Serious",
    "composition": "足元",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:夏の夏祭り. Mood:ノイズが静かに混ざる。\n夏の夏祭りを思い出しそうになる。\n夜風だけ覚えていた。",
    "image": "images/memory/025.webp",
    "status": "pending"
  },
  "夏の_花火": {
    "no": "026",
    "memoryId": "M026",
    "word1": "夏の",
    "word2": "花火",
    "title": "夏の花火",
    "poem": "月が低く見えた。\nビー玉が最後まで出てこない。\n夜だけが残った。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:夏の花火. Mood:月が低く見えた。\nビー玉が最後まで出てこない。\n夜だけが残った。",
    "image": "images/memory/026.webp",
    "status": "pending"
  },
  "夏の_ラムネ": {
    "no": "027",
    "memoryId": "M027",
    "word1": "夏の",
    "word2": "ラムネ",
    "title": "夏のラムネ",
    "poem": "汗が少し乾いた。\n夏のラムネを思い出しそうになる。\n指だけ頑張っていた。",
    "mood": "Serious",
    "composition": "足元",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:夏のラムネ. Mood:汗が少し乾いた。\n夏のラムネを思い出しそうになる。\n指だけ頑張っていた。",
    "image": "images/memory/027.webp",
    "status": "pending"
  },
  "夏の_夕暮れ": {
    "no": "028",
    "memoryId": "M028",
    "word1": "夏の",
    "word2": "夕暮れ",
    "title": "夏の夕暮れ",
    "poem": "夜気がゆっくり近づく。\nビー玉が最後まで出てこない。\n影だけ伸びていた。",
    "mood": "Smile",
    "composition": "鳥居",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:夏の夕暮れ. Mood:夜気がゆっくり近づく。\nビー玉が最後まで出てこない。\n影だけ伸びていた。",
    "image": "images/memory/028.webp",
    "status": "pending"
  },
  "夏の_鳥居": {
    "no": "029",
    "memoryId": "M029",
    "word1": "夏の",
    "word2": "鳥居",
    "title": "夏の鳥居",
    "poem": "空はまだ青かった。\n夏の鳥居を思い出しそうになる。\n足音だけ越えていった。",
    "mood": "Serious",
    "composition": "水面",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:夏の鳥居. Mood:空はまだ青かった。\n夏の鳥居を思い出しそうになる。\n足音だけ越えていった。",
    "image": "images/memory/029.webp",
    "status": "pending"
  },
  "夏の_灯籠": {
    "no": "030",
    "memoryId": "M030",
    "word1": "夏の",
    "word2": "灯籠",
    "title": "夏の灯籠",
    "poem": "空はまだ青かった。\n扇風機に向かって『あー』と言いたくなった。\n灯りだけ残っていた。",
    "mood": "Smile",
    "composition": "手元",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:夏の灯籠. Mood:空はまだ青かった。\n扇風機に向かって『あー』と言いたくなった。\n灯りだけ残っていた。",
    "image": "images/memory/030.webp",
    "status": "pending"
  },
  "夏の_河川敷": {
    "no": "031",
    "memoryId": "M031",
    "word1": "夏の",
    "word2": "河川敷",
    "title": "夏の河川敷",
    "poem": "空はまだ青かった。\n夏の河川敷を思い出しそうになる。\n風だけ遊んでいた。",
    "mood": "Serious",
    "composition": "横顔",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:夏の河川敷. Mood:空はまだ青かった。\n夏の河川敷を思い出しそうになる。\n風だけ遊んでいた。",
    "image": "images/memory/031.webp",
    "status": "pending"
  },
  "夏の_蝉時雨": {
    "no": "032",
    "memoryId": "M032",
    "word1": "夏の",
    "word2": "蝉時雨",
    "title": "夏の蝉時雨",
    "poem": "月が低く見えた。\n屋台の匂いに負けた。\n木陰だけ涼しかった。",
    "mood": "Smile",
    "composition": "横顔",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:夏の蝉時雨. Mood:月が低く見えた。\n屋台の匂いに負けた。\n木陰だけ涼しかった。",
    "image": "images/memory/032.webp",
    "status": "pending"
  },
  "夏の_祭り囃子": {
    "no": "033",
    "memoryId": "M033",
    "word1": "夏の",
    "word2": "祭り囃子",
    "title": "夏の祭り囃子",
    "poem": "月が低く見えた。\n夏の祭り囃子を思い出しそうになる。\n太鼓だけ急いでいた。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:夏の祭り囃子. Mood:月が低く見えた。\n夏の祭り囃子を思い出しそうになる。\n太鼓だけ急いでいた。",
    "image": "images/memory/033.webp",
    "status": "pending"
  },
  "夏の_帰り道": {
    "no": "034",
    "memoryId": "M034",
    "word1": "夏の",
    "word2": "帰り道",
    "title": "夏の帰り道",
    "poem": "風鈴がひとつ鳴った。\n扇風機に向かって『あー』と言いたくなった。\n街灯だけ待っていた。",
    "mood": "Smile",
    "composition": "手元",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:夏の帰り道. Mood:風鈴がひとつ鳴った。\n扇風機に向かって『あー』と言いたくなった。\n街灯だけ待っていた。",
    "image": "images/memory/034.webp",
    "status": "pending"
  },
  "夏の_夜店": {
    "no": "035",
    "memoryId": "M035",
    "word1": "夏の",
    "word2": "夜店",
    "title": "夏の夜店",
    "poem": "風が少し止んだ。\n夏の夜店を思い出しそうになる。\nお腹だけ急いでいた。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:夏の夜店. Mood:風が少し止んだ。\n夏の夜店を思い出しそうになる。\nお腹だけ急いでいた。",
    "image": "images/memory/035.webp",
    "status": "pending"
  },
  "夏の_打ち上げ跡": {
    "no": "036",
    "memoryId": "M036",
    "word1": "夏の",
    "word2": "打ち上げ跡",
    "title": "夏の打ち上げ跡",
    "poem": "ノイズが静かに混ざる。\nラムネの泡だけ元気だった。\n静けさだけ広がった。",
    "mood": "Smile",
    "composition": "鳥居",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:夏の打ち上げ跡. Mood:ノイズが静かに混ざる。\nラムネの泡だけ元気だった。\n静けさだけ広がった。",
    "image": "images/memory/036.webp",
    "status": "pending"
  },
  "見つからない_夏祭り": {
    "no": "037",
    "memoryId": "M037",
    "word1": "見つからない",
    "word2": "夏祭り",
    "title": "見つからない夏祭り",
    "poem": "風が少し止んだ。\n見つからない夏祭りを思い出しそうになる。\n提灯だけが揺れていた。",
    "mood": "Serious",
    "composition": "鳥居",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:見つからない夏祭り. Mood:風が少し止んだ。\n見つからない夏祭りを思い出しそうになる。\n提灯だけが揺れていた。",
    "image": "images/memory/037.webp",
    "status": "pending"
  },
  "見つからない_花火": {
    "no": "038",
    "memoryId": "M038",
    "word1": "見つからない",
    "word2": "花火",
    "title": "見つからない花火",
    "poem": "風が少し止んだ。\nサンダルに小石が入った。\n夜だけが残った。",
    "mood": "Smile",
    "composition": "手元",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:見つからない花火. Mood:風が少し止んだ。\nサンダルに小石が入った。\n夜だけが残った。",
    "image": "images/memory/038.webp",
    "status": "pending"
  },
  "見つからない_ラムネ": {
    "no": "039",
    "memoryId": "M039",
    "word1": "見つからない",
    "word2": "ラムネ",
    "title": "見つからないラムネ",
    "poem": "ノイズが静かに混ざる。\n見つからないラムネを思い出しそうになる。\nビー玉だけ帰らなかった。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:見つからないラムネ. Mood:ノイズが静かに混ざる。\n見つからないラムネを思い出しそうになる。\nビー玉だけ帰らなかった。",
    "image": "images/memory/039.webp",
    "status": "pending"
  },
  "見つからない_夕暮れ": {
    "no": "040",
    "memoryId": "M040",
    "word1": "見つからない",
    "word2": "夕暮れ",
    "title": "見つからない夕暮れ",
    "poem": "空はまだ青かった。\n屋台の匂いに負けた。\n風だけ知っていた。",
    "mood": "Smile",
    "composition": "空",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:見つからない夕暮れ. Mood:空はまだ青かった。\n屋台の匂いに負けた。\n風だけ知っていた。",
    "image": "images/memory/040.webp",
    "status": "pending"
  },
  "見つからない_鳥居": {
    "no": "041",
    "memoryId": "M041",
    "word1": "見つからない",
    "word2": "鳥居",
    "title": "見つからない鳥居",
    "poem": "風が少し止んだ。\n見つからない鳥居を思い出しそうになる。\n足音だけ越えていった。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:見つからない鳥居. Mood:風が少し止んだ。\n見つからない鳥居を思い出しそうになる。\n足音だけ越えていった。",
    "image": "images/memory/041.webp",
    "status": "pending"
  },
  "見つからない_灯籠": {
    "no": "042",
    "memoryId": "M042",
    "word1": "見つからない",
    "word2": "灯籠",
    "title": "見つからない灯籠",
    "poem": "風が少し止んだ。\n屋台の匂いに負けた。\n水面だけ応えていた。",
    "mood": "Smile",
    "composition": "手元",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:見つからない灯籠. Mood:風が少し止んだ。\n屋台の匂いに負けた。\n水面だけ応えていた。",
    "image": "images/memory/042.webp",
    "status": "pending"
  },
  "見つからない_河川敷": {
    "no": "043",
    "memoryId": "M043",
    "word1": "見つからない",
    "word2": "河川敷",
    "title": "見つからない河川敷",
    "poem": "空はまだ青かった。\n見つからない河川敷を思い出しそうになる。\n水面だけ笑っていた。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:見つからない河川敷. Mood:空はまだ青かった。\n見つからない河川敷を思い出しそうになる。\n水面だけ笑っていた。",
    "image": "images/memory/043.webp",
    "status": "pending"
  },
  "見つからない_蝉時雨": {
    "no": "044",
    "memoryId": "M044",
    "word1": "見つからない",
    "word2": "蝉時雨",
    "title": "見つからない蝉時雨",
    "poem": "灯りが水面にほどける。\nサンダルに小石が入った。\n空だけ静かだった。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:見つからない蝉時雨. Mood:灯りが水面にほどける。\nサンダルに小石が入った。\n空だけ静かだった。",
    "image": "images/memory/044.webp",
    "status": "pending"
  },
  "見つからない_祭り囃子": {
    "no": "045",
    "memoryId": "M045",
    "word1": "見つからない",
    "word2": "祭り囃子",
    "title": "見つからない祭り囃子",
    "poem": "灯りが水面にほどける。\n見つからない祭り囃子を思い出しそうになる。\n太鼓だけ急いでいた。",
    "mood": "Serious",
    "composition": "水面",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:見つからない祭り囃子. Mood:灯りが水面にほどける。\n見つからない祭り囃子を思い出しそうになる。\n太鼓だけ急いでいた。",
    "image": "images/memory/045.webp",
    "status": "pending"
  },
  "見つからない_帰り道": {
    "no": "046",
    "memoryId": "M046",
    "word1": "見つからない",
    "word2": "帰り道",
    "title": "見つからない帰り道",
    "poem": "風鈴がひとつ鳴った。\nラムネの泡だけ元気だった。\n靴音だけ続いていた。",
    "mood": "Smile",
    "composition": "空",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:見つからない帰り道. Mood:風鈴がひとつ鳴った。\nラムネの泡だけ元気だった。\n靴音だけ続いていた。",
    "image": "images/memory/046.webp",
    "status": "pending"
  },
  "見つからない_夜店": {
    "no": "047",
    "memoryId": "M047",
    "word1": "見つからない",
    "word2": "夜店",
    "title": "見つからない夜店",
    "poem": "風鈴がひとつ鳴った。\n見つからない夜店を思い出しそうになる。\n匂いだけ笑っていた。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:見つからない夜店. Mood:風鈴がひとつ鳴った。\n見つからない夜店を思い出しそうになる。\n匂いだけ笑っていた。",
    "image": "images/memory/047.webp",
    "status": "pending"
  },
  "見つからない_打ち上げ跡": {
    "no": "048",
    "memoryId": "M048",
    "word1": "見つからない",
    "word2": "打ち上げ跡",
    "title": "見つからない打ち上げ跡",
    "poem": "汗が少し乾いた。\n屋台の匂いに負けた。\n静けさだけ広がった。",
    "mood": "Smile",
    "composition": "手元",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:見つからない打ち上げ跡. Mood:汗が少し乾いた。\n屋台の匂いに負けた。\n静けさだけ広がった。",
    "image": "images/memory/048.webp",
    "status": "pending"
  },
  "まだ帰れない_夏祭り": {
    "no": "049",
    "memoryId": "M049",
    "word1": "まだ帰れない",
    "word2": "夏祭り",
    "title": "まだ帰れない夏祭り",
    "poem": "風鈴がひとつ鳴った。\nまだ帰れない夏祭りを思い出しそうになる。\n夜風だけ覚えていた。",
    "mood": "Serious",
    "composition": "足元",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:まだ帰れない夏祭り. Mood:風鈴がひとつ鳴った。\nまだ帰れない夏祭りを思い出しそうになる。\n夜風だけ覚えていた。",
    "image": "images/memory/049.webp",
    "status": "pending"
  },
  "まだ帰れない_花火": {
    "no": "050",
    "memoryId": "M050",
    "word1": "まだ帰れない",
    "word2": "花火",
    "title": "まだ帰れない花火",
    "poem": "汗が少し乾いた。\n線香花火をまだ信じていた。\n光だけ笑っていた。",
    "mood": "Smile",
    "composition": "空",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:まだ帰れない花火. Mood:汗が少し乾いた。\n線香花火をまだ信じていた。\n光だけ笑っていた。",
    "image": "images/memory/050.webp",
    "status": "pending"
  },
  "まだ帰れない_ラムネ": {
    "no": "051",
    "memoryId": "M051",
    "word1": "まだ帰れない",
    "word2": "ラムネ",
    "title": "まだ帰れないラムネ",
    "poem": "空はまだ青かった。\nまだ帰れないラムネを思い出しそうになる。\n甘さだけ残った。",
    "mood": "Serious",
    "composition": "足元",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:まだ帰れないラムネ. Mood:空はまだ青かった。\nまだ帰れないラムネを思い出しそうになる。\n甘さだけ残った。",
    "image": "images/memory/051.webp",
    "status": "pending"
  },
  "まだ帰れない_夕暮れ": {
    "no": "052",
    "memoryId": "M052",
    "word1": "まだ帰れない",
    "word2": "夕暮れ",
    "title": "まだ帰れない夕暮れ",
    "poem": "汗が少し乾いた。\n扇風機に向かって『あー』と言いたくなった。\n風だけ知っていた。",
    "mood": "Smile",
    "composition": "横顔",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:まだ帰れない夕暮れ. Mood:汗が少し乾いた。\n扇風機に向かって『あー』と言いたくなった。\n風だけ知っていた。",
    "image": "images/memory/052.webp",
    "status": "pending"
  },
  "まだ帰れない_鳥居": {
    "no": "053",
    "memoryId": "M053",
    "word1": "まだ帰れない",
    "word2": "鳥居",
    "title": "まだ帰れない鳥居",
    "poem": "空はまだ青かった。\nまだ帰れない鳥居を思い出しそうになる。\n足音だけ越えていった。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:まだ帰れない鳥居. Mood:空はまだ青かった。\nまだ帰れない鳥居を思い出しそうになる。\n足音だけ越えていった。",
    "image": "images/memory/053.webp",
    "status": "pending"
  },
  "まだ帰れない_灯籠": {
    "no": "054",
    "memoryId": "M054",
    "word1": "まだ帰れない",
    "word2": "灯籠",
    "title": "まだ帰れない灯籠",
    "poem": "夜気がゆっくり近づく。\n扇風機に向かって『あー』と言いたくなった。\n灯りだけ残っていた。",
    "mood": "Smile",
    "composition": "足元",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:まだ帰れない灯籠. Mood:夜気がゆっくり近づく。\n扇風機に向かって『あー』と言いたくなった。\n灯りだけ残っていた。",
    "image": "images/memory/054.webp",
    "status": "pending"
  },
  "まだ帰れない_河川敷": {
    "no": "055",
    "memoryId": "M055",
    "word1": "まだ帰れない",
    "word2": "河川敷",
    "title": "まだ帰れない河川敷",
    "poem": "汗が少し乾いた。\nまだ帰れない河川敷を思い出しそうになる。\n風だけ遊んでいた。",
    "mood": "Serious",
    "composition": "手元",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:まだ帰れない河川敷. Mood:汗が少し乾いた。\nまだ帰れない河川敷を思い出しそうになる。\n風だけ遊んでいた。",
    "image": "images/memory/055.webp",
    "status": "pending"
  },
  "まだ帰れない_蝉時雨": {
    "no": "056",
    "memoryId": "M056",
    "word1": "まだ帰れない",
    "word2": "蝉時雨",
    "title": "まだ帰れない蝉時雨",
    "poem": "汗が少し乾いた。\n線香花火をまだ信じていた。\n音だけ夏だった。",
    "mood": "Smile",
    "composition": "後ろ姿",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:まだ帰れない蝉時雨. Mood:汗が少し乾いた。\n線香花火をまだ信じていた。\n音だけ夏だった。",
    "image": "images/memory/056.webp",
    "status": "pending"
  },
  "まだ帰れない_祭り囃子": {
    "no": "057",
    "memoryId": "M057",
    "word1": "まだ帰れない",
    "word2": "祭り囃子",
    "title": "まだ帰れない祭り囃子",
    "poem": "空はまだ青かった。\nまだ帰れない祭り囃子を思い出しそうになる。\n太鼓だけ急いでいた。",
    "mood": "Serious",
    "composition": "鳥居",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:まだ帰れない祭り囃子. Mood:空はまだ青かった。\nまだ帰れない祭り囃子を思い出しそうになる。\n太鼓だけ急いでいた。",
    "image": "images/memory/057.webp",
    "status": "pending"
  },
  "まだ帰れない_帰り道": {
    "no": "058",
    "memoryId": "M058",
    "word1": "まだ帰れない",
    "word2": "帰り道",
    "title": "まだ帰れない帰り道",
    "poem": "ノイズが静かに混ざる。\nサンダルに小石が入った。\n街灯だけ待っていた。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:まだ帰れない帰り道. Mood:ノイズが静かに混ざる。\nサンダルに小石が入った。\n街灯だけ待っていた。",
    "image": "images/memory/058.webp",
    "status": "pending"
  },
  "まだ帰れない_夜店": {
    "no": "059",
    "memoryId": "M059",
    "word1": "まだ帰れない",
    "word2": "夜店",
    "title": "まだ帰れない夜店",
    "poem": "汗が少し乾いた。\nまだ帰れない夜店を思い出しそうになる。\n匂いだけ笑っていた。",
    "mood": "Serious",
    "composition": "横顔",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:まだ帰れない夜店. Mood:汗が少し乾いた。\nまだ帰れない夜店を思い出しそうになる。\n匂いだけ笑っていた。",
    "image": "images/memory/059.webp",
    "status": "pending"
  },
  "まだ帰れない_打ち上げ跡": {
    "no": "060",
    "memoryId": "M060",
    "word1": "まだ帰れない",
    "word2": "打ち上げ跡",
    "title": "まだ帰れない打ち上げ跡",
    "poem": "夜気がゆっくり近づく。\nサンダルに小石が入った。\n静けさだけ広がった。",
    "mood": "Smile",
    "composition": "鳥居",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:まだ帰れない打ち上げ跡. Mood:夜気がゆっくり近づく。\nサンダルに小石が入った。\n静けさだけ広がった。",
    "image": "images/memory/060.webp",
    "status": "pending"
  },
  "遠い_夏祭り": {
    "no": "061",
    "memoryId": "M061",
    "word1": "遠い",
    "word2": "夏祭り",
    "title": "遠い夏祭り",
    "poem": "ノイズが静かに混ざる。\n遠い夏祭りを思い出しそうになる。\n笑い声だけ残った。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:遠い夏祭り. Mood:ノイズが静かに混ざる。\n遠い夏祭りを思い出しそうになる。\n笑い声だけ残った。",
    "image": "images/memory/061.webp",
    "status": "pending"
  },
  "遠い_花火": {
    "no": "062",
    "memoryId": "M062",
    "word1": "遠い",
    "word2": "花火",
    "title": "遠い花火",
    "poem": "空はまだ青かった。\n線香花火をまだ信じていた。\n光だけ笑っていた。",
    "mood": "Smile",
    "composition": "空",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:遠い花火. Mood:空はまだ青かった。\n線香花火をまだ信じていた。\n光だけ笑っていた。",
    "image": "images/memory/062.webp",
    "status": "pending"
  },
  "遠い_ラムネ": {
    "no": "063",
    "memoryId": "M063",
    "word1": "遠い",
    "word2": "ラムネ",
    "title": "遠いラムネ",
    "poem": "風鈴がひとつ鳴った。\n遠いラムネを思い出しそうになる。\n指だけ頑張っていた。",
    "mood": "Serious",
    "composition": "横顔",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:遠いラムネ. Mood:風鈴がひとつ鳴った。\n遠いラムネを思い出しそうになる。\n指だけ頑張っていた。",
    "image": "images/memory/063.webp",
    "status": "pending"
  },
  "遠い_夕暮れ": {
    "no": "064",
    "memoryId": "M064",
    "word1": "遠い",
    "word2": "夕暮れ",
    "title": "遠い夕暮れ",
    "poem": "夜気がゆっくり近づく。\n扇風機に向かって『あー』と言いたくなった。\n影だけ伸びていた。",
    "mood": "Smile",
    "composition": "後ろ姿",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:遠い夕暮れ. Mood:夜気がゆっくり近づく。\n扇風機に向かって『あー』と言いたくなった。\n影だけ伸びていた。",
    "image": "images/memory/064.webp",
    "status": "pending"
  },
  "遠い_鳥居": {
    "no": "065",
    "memoryId": "M065",
    "word1": "遠い",
    "word2": "鳥居",
    "title": "遠い鳥居",
    "poem": "灯りが水面にほどける。\n遠い鳥居を思い出しそうになる。\n足音だけ越えていった。",
    "mood": "Serious",
    "composition": "足元",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:遠い鳥居. Mood:灯りが水面にほどける。\n遠い鳥居を思い出しそうになる。\n足音だけ越えていった。",
    "image": "images/memory/065.webp",
    "status": "pending"
  },
  "遠い_灯籠": {
    "no": "066",
    "memoryId": "M066",
    "word1": "遠い",
    "word2": "灯籠",
    "title": "遠い灯籠",
    "poem": "空はまだ青かった。\nサンダルに小石が入った。\n光だけ流れていた。",
    "mood": "Smile",
    "composition": "足元",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:遠い灯籠. Mood:空はまだ青かった。\nサンダルに小石が入った。\n光だけ流れていた。",
    "image": "images/memory/066.webp",
    "status": "pending"
  },
  "遠い_河川敷": {
    "no": "067",
    "memoryId": "M067",
    "word1": "遠い",
    "word2": "河川敷",
    "title": "遠い河川敷",
    "poem": "汗が少し乾いた。\n遠い河川敷を思い出しそうになる。\n水面だけ笑っていた。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:遠い河川敷. Mood:汗が少し乾いた。\n遠い河川敷を思い出しそうになる。\n水面だけ笑っていた。",
    "image": "images/memory/067.webp",
    "status": "pending"
  },
  "遠い_蝉時雨": {
    "no": "068",
    "memoryId": "M068",
    "word1": "遠い",
    "word2": "蝉時雨",
    "title": "遠い蝉時雨",
    "poem": "汗が少し乾いた。\nビー玉が最後まで出てこない。\n空だけ静かだった。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:遠い蝉時雨. Mood:汗が少し乾いた。\nビー玉が最後まで出てこない。\n空だけ静かだった。",
    "image": "images/memory/068.webp",
    "status": "pending"
  },
  "遠い_祭り囃子": {
    "no": "069",
    "memoryId": "M069",
    "word1": "遠い",
    "word2": "祭り囃子",
    "title": "遠い祭り囃子",
    "poem": "風鈴がひとつ鳴った。\n遠い祭り囃子を思い出しそうになる。\n夜だけ踊っていた。",
    "mood": "Serious",
    "composition": "足元",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:遠い祭り囃子. Mood:風鈴がひとつ鳴った。\n遠い祭り囃子を思い出しそうになる。\n夜だけ踊っていた。",
    "image": "images/memory/069.webp",
    "status": "pending"
  },
  "遠い_帰り道": {
    "no": "070",
    "memoryId": "M070",
    "word1": "遠い",
    "word2": "帰り道",
    "title": "遠い帰り道",
    "poem": "灯りが水面にほどける。\n扇風機に向かって『あー』と言いたくなった。\n街灯だけ待っていた。",
    "mood": "Smile",
    "composition": "空",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:遠い帰り道. Mood:灯りが水面にほどける。\n扇風機に向かって『あー』と言いたくなった。\n街灯だけ待っていた。",
    "image": "images/memory/070.webp",
    "status": "pending"
  },
  "遠い_夜店": {
    "no": "071",
    "memoryId": "M071",
    "word1": "遠い",
    "word2": "夜店",
    "title": "遠い夜店",
    "poem": "風鈴がひとつ鳴った。\n遠い夜店を思い出しそうになる。\nお腹だけ急いでいた。",
    "mood": "Serious",
    "composition": "水面",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:遠い夜店. Mood:風鈴がひとつ鳴った。\n遠い夜店を思い出しそうになる。\nお腹だけ急いでいた。",
    "image": "images/memory/071.webp",
    "status": "pending"
  },
  "遠い_打ち上げ跡": {
    "no": "072",
    "memoryId": "M072",
    "word1": "遠い",
    "word2": "打ち上げ跡",
    "title": "遠い打ち上げ跡",
    "poem": "灯りが水面にほどける。\nサンダルに小石が入った。\n火薬の匂いだけ残った。",
    "mood": "Smile",
    "composition": "手元",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:遠い打ち上げ跡. Mood:灯りが水面にほどける。\nサンダルに小石が入った。\n火薬の匂いだけ残った。",
    "image": "images/memory/072.webp",
    "status": "pending"
  },
  "名前のない_夏祭り": {
    "no": "073",
    "memoryId": "M073",
    "word1": "名前のない",
    "word2": "夏祭り",
    "title": "名前のない夏祭り",
    "poem": "汗が少し乾いた。\n名前のない夏祭りを思い出しそうになる。\n夜風だけ覚えていた。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:名前のない夏祭り. Mood:汗が少し乾いた。\n名前のない夏祭りを思い出しそうになる。\n夜風だけ覚えていた。",
    "image": "images/memory/073.webp",
    "status": "pending"
  },
  "名前のない_花火": {
    "no": "074",
    "memoryId": "M074",
    "word1": "名前のない",
    "word2": "花火",
    "title": "名前のない花火",
    "poem": "月が低く見えた。\nビー玉が最後まで出てこない。\n夜だけが残った。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:名前のない花火. Mood:月が低く見えた。\nビー玉が最後まで出てこない。\n夜だけが残った。",
    "image": "images/memory/074.webp",
    "status": "pending"
  },
  "名前のない_ラムネ": {
    "no": "075",
    "memoryId": "M075",
    "word1": "名前のない",
    "word2": "ラムネ",
    "title": "名前のないラムネ",
    "poem": "風鈴がひとつ鳴った。\n名前のないラムネを思い出しそうになる。\n甘さだけ残った。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:名前のないラムネ. Mood:風鈴がひとつ鳴った。\n名前のないラムネを思い出しそうになる。\n甘さだけ残った。",
    "image": "images/memory/075.webp",
    "status": "pending"
  },
  "名前のない_夕暮れ": {
    "no": "076",
    "memoryId": "M076",
    "word1": "名前のない",
    "word2": "夕暮れ",
    "title": "名前のない夕暮れ",
    "poem": "夜気がゆっくり近づく。\n扇風機に向かって『あー』と言いたくなった。\n風だけ知っていた。",
    "mood": "Smile",
    "composition": "鳥居",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:名前のない夕暮れ. Mood:夜気がゆっくり近づく。\n扇風機に向かって『あー』と言いたくなった。\n風だけ知っていた。",
    "image": "images/memory/076.webp",
    "status": "pending"
  },
  "名前のない_鳥居": {
    "no": "077",
    "memoryId": "M077",
    "word1": "名前のない",
    "word2": "鳥居",
    "title": "名前のない鳥居",
    "poem": "夜気がゆっくり近づく。\n名前のない鳥居を思い出しそうになる。\n足音だけ越えていった。",
    "mood": "Serious",
    "composition": "横顔",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:名前のない鳥居. Mood:夜気がゆっくり近づく。\n名前のない鳥居を思い出しそうになる。\n足音だけ越えていった。",
    "image": "images/memory/077.webp",
    "status": "pending"
  },
  "名前のない_灯籠": {
    "no": "078",
    "memoryId": "M078",
    "word1": "名前のない",
    "word2": "灯籠",
    "title": "名前のない灯籠",
    "poem": "空はまだ青かった。\n屋台の匂いに負けた。\n光だけ流れていた。",
    "mood": "Smile",
    "composition": "鳥居",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:名前のない灯籠. Mood:空はまだ青かった。\n屋台の匂いに負けた。\n光だけ流れていた。",
    "image": "images/memory/078.webp",
    "status": "pending"
  },
  "名前のない_河川敷": {
    "no": "079",
    "memoryId": "M079",
    "word1": "名前のない",
    "word2": "河川敷",
    "title": "名前のない河川敷",
    "poem": "ノイズが静かに混ざる。\n名前のない河川敷を思い出しそうになる。\n水面だけ笑っていた。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:名前のない河川敷. Mood:ノイズが静かに混ざる。\n名前のない河川敷を思い出しそうになる。\n水面だけ笑っていた。",
    "image": "images/memory/079.webp",
    "status": "pending"
  },
  "名前のない_蝉時雨": {
    "no": "080",
    "memoryId": "M080",
    "word1": "名前のない",
    "word2": "蝉時雨",
    "title": "名前のない蝉時雨",
    "poem": "月が低く見えた。\n線香花火をまだ信じていた。\n木陰だけ涼しかった。",
    "mood": "Smile",
    "composition": "横顔",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:名前のない蝉時雨. Mood:月が低く見えた。\n線香花火をまだ信じていた。\n木陰だけ涼しかった。",
    "image": "images/memory/080.webp",
    "status": "pending"
  },
  "名前のない_祭り囃子": {
    "no": "081",
    "memoryId": "M081",
    "word1": "名前のない",
    "word2": "祭り囃子",
    "title": "名前のない祭り囃子",
    "poem": "ノイズが静かに混ざる。\n名前のない祭り囃子を思い出しそうになる。\n音だけ帰らなかった。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:名前のない祭り囃子. Mood:ノイズが静かに混ざる。\n名前のない祭り囃子を思い出しそうになる。\n音だけ帰らなかった。",
    "image": "images/memory/081.webp",
    "status": "pending"
  },
  "名前のない_帰り道": {
    "no": "082",
    "memoryId": "M082",
    "word1": "名前のない",
    "word2": "帰り道",
    "title": "名前のない帰り道",
    "poem": "ノイズが静かに混ざる。\nサンダルに小石が入った。\n街灯だけ待っていた。",
    "mood": "Smile",
    "composition": "鳥居",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:名前のない帰り道. Mood:ノイズが静かに混ざる。\nサンダルに小石が入った。\n街灯だけ待っていた。",
    "image": "images/memory/082.webp",
    "status": "pending"
  },
  "名前のない_夜店": {
    "no": "083",
    "memoryId": "M083",
    "word1": "名前のない",
    "word2": "夜店",
    "title": "名前のない夜店",
    "poem": "夜気がゆっくり近づく。\n名前のない夜店を思い出しそうになる。\n財布だけ静かだった。",
    "mood": "Serious",
    "composition": "横顔",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:名前のない夜店. Mood:夜気がゆっくり近づく。\n名前のない夜店を思い出しそうになる。\n財布だけ静かだった。",
    "image": "images/memory/083.webp",
    "status": "pending"
  },
  "名前のない_打ち上げ跡": {
    "no": "084",
    "memoryId": "M084",
    "word1": "名前のない",
    "word2": "打ち上げ跡",
    "title": "名前のない打ち上げ跡",
    "poem": "風が少し止んだ。\nビー玉が最後まで出てこない。\n煙だけ知っていた。",
    "mood": "Smile",
    "composition": "空",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:名前のない打ち上げ跡. Mood:風が少し止んだ。\nビー玉が最後まで出てこない。\n煙だけ知っていた。",
    "image": "images/memory/084.webp",
    "status": "pending"
  },
  "誰にも言えない_夏祭り": {
    "no": "085",
    "memoryId": "M085",
    "word1": "誰にも言えない",
    "word2": "夏祭り",
    "title": "誰にも言えない夏祭り",
    "poem": "夜気がゆっくり近づく。\n誰にも言えない夏祭りを思い出しそうになる。\n夜風だけ覚えていた。",
    "mood": "Serious",
    "composition": "足元",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:誰にも言えない夏祭り. Mood:夜気がゆっくり近づく。\n誰にも言えない夏祭りを思い出しそうになる。\n夜風だけ覚えていた。",
    "image": "images/memory/085.webp",
    "status": "pending"
  },
  "誰にも言えない_花火": {
    "no": "086",
    "memoryId": "M086",
    "word1": "誰にも言えない",
    "word2": "花火",
    "title": "誰にも言えない花火",
    "poem": "風が少し止んだ。\n屋台の匂いに負けた。\n夜だけが残った。",
    "mood": "Smile",
    "composition": "足元",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:誰にも言えない花火. Mood:風が少し止んだ。\n屋台の匂いに負けた。\n夜だけが残った。",
    "image": "images/memory/086.webp",
    "status": "pending"
  },
  "誰にも言えない_ラムネ": {
    "no": "087",
    "memoryId": "M087",
    "word1": "誰にも言えない",
    "word2": "ラムネ",
    "title": "誰にも言えないラムネ",
    "poem": "夜気がゆっくり近づく。\n誰にも言えないラムネを思い出しそうになる。\n指だけ頑張っていた。",
    "mood": "Serious",
    "composition": "足元",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:誰にも言えないラムネ. Mood:夜気がゆっくり近づく。\n誰にも言えないラムネを思い出しそうになる。\n指だけ頑張っていた。",
    "image": "images/memory/087.webp",
    "status": "pending"
  },
  "誰にも言えない_夕暮れ": {
    "no": "088",
    "memoryId": "M088",
    "word1": "誰にも言えない",
    "word2": "夕暮れ",
    "title": "誰にも言えない夕暮れ",
    "poem": "風鈴がひとつ鳴った。\n屋台の匂いに負けた。\n影だけ伸びていた。",
    "mood": "Smile",
    "composition": "後ろ姿",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:誰にも言えない夕暮れ. Mood:風鈴がひとつ鳴った。\n屋台の匂いに負けた。\n影だけ伸びていた。",
    "image": "images/memory/088.webp",
    "status": "pending"
  },
  "誰にも言えない_鳥居": {
    "no": "089",
    "memoryId": "M089",
    "word1": "誰にも言えない",
    "word2": "鳥居",
    "title": "誰にも言えない鳥居",
    "poem": "空はまだ青かった。\n誰にも言えない鳥居を思い出しそうになる。\n足音だけ越えていった。",
    "mood": "Serious",
    "composition": "鳥居",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:誰にも言えない鳥居. Mood:空はまだ青かった。\n誰にも言えない鳥居を思い出しそうになる。\n足音だけ越えていった。",
    "image": "images/memory/089.webp",
    "status": "pending"
  },
  "誰にも言えない_灯籠": {
    "no": "090",
    "memoryId": "M090",
    "word1": "誰にも言えない",
    "word2": "灯籠",
    "title": "誰にも言えない灯籠",
    "poem": "ノイズが静かに混ざる。\nラムネの泡だけ元気だった。\n光だけ流れていた。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:誰にも言えない灯籠. Mood:ノイズが静かに混ざる。\nラムネの泡だけ元気だった。\n光だけ流れていた。",
    "image": "images/memory/090.webp",
    "status": "pending"
  },
  "誰にも言えない_河川敷": {
    "no": "091",
    "memoryId": "M091",
    "word1": "誰にも言えない",
    "word2": "河川敷",
    "title": "誰にも言えない河川敷",
    "poem": "灯りが水面にほどける。\n誰にも言えない河川敷を思い出しそうになる。\n水面だけ笑っていた。",
    "mood": "Serious",
    "composition": "水面",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:誰にも言えない河川敷. Mood:灯りが水面にほどける。\n誰にも言えない河川敷を思い出しそうになる。\n水面だけ笑っていた。",
    "image": "images/memory/091.webp",
    "status": "pending"
  },
  "誰にも言えない_蝉時雨": {
    "no": "092",
    "memoryId": "M092",
    "word1": "誰にも言えない",
    "word2": "蝉時雨",
    "title": "誰にも言えない蝉時雨",
    "poem": "夜気がゆっくり近づく。\n扇風機に向かって『あー』と言いたくなった。\n木陰だけ涼しかった。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:誰にも言えない蝉時雨. Mood:夜気がゆっくり近づく。\n扇風機に向かって『あー』と言いたくなった。\n木陰だけ涼しかった。",
    "image": "images/memory/092.webp",
    "status": "pending"
  },
  "誰にも言えない_祭り囃子": {
    "no": "093",
    "memoryId": "M093",
    "word1": "誰にも言えない",
    "word2": "祭り囃子",
    "title": "誰にも言えない祭り囃子",
    "poem": "風鈴がひとつ鳴った。\n誰にも言えない祭り囃子を思い出しそうになる。\n太鼓だけ急いでいた。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:誰にも言えない祭り囃子. Mood:風鈴がひとつ鳴った。\n誰にも言えない祭り囃子を思い出しそうになる。\n太鼓だけ急いでいた。",
    "image": "images/memory/093.webp",
    "status": "pending"
  },
  "誰にも言えない_帰り道": {
    "no": "094",
    "memoryId": "M094",
    "word1": "誰にも言えない",
    "word2": "帰り道",
    "title": "誰にも言えない帰り道",
    "poem": "汗が少し乾いた。\n線香花火をまだ信じていた。\n靴音だけ続いていた。",
    "mood": "Smile",
    "composition": "手元",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:誰にも言えない帰り道. Mood:汗が少し乾いた。\n線香花火をまだ信じていた。\n靴音だけ続いていた。",
    "image": "images/memory/094.webp",
    "status": "pending"
  },
  "誰にも言えない_夜店": {
    "no": "095",
    "memoryId": "M095",
    "word1": "誰にも言えない",
    "word2": "夜店",
    "title": "誰にも言えない夜店",
    "poem": "月が低く見えた。\n誰にも言えない夜店を思い出しそうになる。\n匂いだけ笑っていた。",
    "mood": "Serious",
    "composition": "手元",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:誰にも言えない夜店. Mood:月が低く見えた。\n誰にも言えない夜店を思い出しそうになる。\n匂いだけ笑っていた。",
    "image": "images/memory/095.webp",
    "status": "pending"
  },
  "誰にも言えない_打ち上げ跡": {
    "no": "096",
    "memoryId": "M096",
    "word1": "誰にも言えない",
    "word2": "打ち上げ跡",
    "title": "誰にも言えない打ち上げ跡",
    "poem": "夜気がゆっくり近づく。\n屋台の匂いに負けた。\n煙だけ知っていた。",
    "mood": "Smile",
    "composition": "後ろ姿",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:誰にも言えない打ち上げ跡. Mood:夜気がゆっくり近づく。\n屋台の匂いに負けた。\n煙だけ知っていた。",
    "image": "images/memory/096.webp",
    "status": "pending"
  },
  "接続不能の_夏祭り": {
    "no": "097",
    "memoryId": "M097",
    "word1": "接続不能の",
    "word2": "夏祭り",
    "title": "接続不能の夏祭り",
    "poem": "空はまだ青かった。\n接続不能の夏祭りを思い出しそうになる。\n笑い声だけ残った。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:接続不能の夏祭り. Mood:空はまだ青かった。\n接続不能の夏祭りを思い出しそうになる。\n笑い声だけ残った。",
    "image": "images/memory/097.webp",
    "status": "pending"
  },
  "接続不能の_花火": {
    "no": "098",
    "memoryId": "M098",
    "word1": "接続不能の",
    "word2": "花火",
    "title": "接続不能の花火",
    "poem": "月が低く見えた。\nラムネの泡だけ元気だった。\n空だけ覚えていた。",
    "mood": "Smile",
    "composition": "後ろ姿",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:接続不能の花火. Mood:月が低く見えた。\nラムネの泡だけ元気だった。\n空だけ覚えていた。",
    "image": "images/memory/098.webp",
    "status": "pending"
  },
  "接続不能の_ラムネ": {
    "no": "099",
    "memoryId": "M099",
    "word1": "接続不能の",
    "word2": "ラムネ",
    "title": "接続不能のラムネ",
    "poem": "空はまだ青かった。\n接続不能のラムネを思い出しそうになる。\n甘さだけ残った。",
    "mood": "Serious",
    "composition": "水面",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:接続不能のラムネ. Mood:空はまだ青かった。\n接続不能のラムネを思い出しそうになる。\n甘さだけ残った。",
    "image": "images/memory/099.webp",
    "status": "pending"
  },
  "接続不能の_夕暮れ": {
    "no": "100",
    "memoryId": "M100",
    "word1": "接続不能の",
    "word2": "夕暮れ",
    "title": "接続不能の夕暮れ",
    "poem": "夜気がゆっくり近づく。\nビー玉が最後まで出てこない。\n影だけ伸びていた。",
    "mood": "Smile",
    "composition": "足元",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:接続不能の夕暮れ. Mood:夜気がゆっくり近づく。\nビー玉が最後まで出てこない。\n影だけ伸びていた。",
    "image": "images/memory/100.webp",
    "status": "pending"
  },
  "接続不能の_鳥居": {
    "no": "101",
    "memoryId": "M101",
    "word1": "接続不能の",
    "word2": "鳥居",
    "title": "接続不能の鳥居",
    "poem": "風鈴がひとつ鳴った。\n接続不能の鳥居を思い出しそうになる。\n境界だけ揺れていた。",
    "mood": "Serious",
    "composition": "手元",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:接続不能の鳥居. Mood:風鈴がひとつ鳴った。\n接続不能の鳥居を思い出しそうになる。\n境界だけ揺れていた。",
    "image": "images/memory/101.webp",
    "status": "pending"
  },
  "接続不能の_灯籠": {
    "no": "102",
    "memoryId": "M102",
    "word1": "接続不能の",
    "word2": "灯籠",
    "title": "接続不能の灯籠",
    "poem": "風鈴がひとつ鳴った。\nサンダルに小石が入った。\n水面だけ応えていた。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:接続不能の灯籠. Mood:風鈴がひとつ鳴った。\nサンダルに小石が入った。\n水面だけ応えていた。",
    "image": "images/memory/102.webp",
    "status": "pending"
  },
  "接続不能の_河川敷": {
    "no": "103",
    "memoryId": "M103",
    "word1": "接続不能の",
    "word2": "河川敷",
    "title": "接続不能の河川敷",
    "poem": "汗が少し乾いた。\n接続不能の河川敷を思い出しそうになる。\n風だけ遊んでいた。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:接続不能の河川敷. Mood:汗が少し乾いた。\n接続不能の河川敷を思い出しそうになる。\n風だけ遊んでいた。",
    "image": "images/memory/103.webp",
    "status": "pending"
  },
  "接続不能の_蝉時雨": {
    "no": "104",
    "memoryId": "M104",
    "word1": "接続不能の",
    "word2": "蝉時雨",
    "title": "接続不能の蝉時雨",
    "poem": "月が低く見えた。\nラムネの泡だけ元気だった。\n空だけ静かだった。",
    "mood": "Smile",
    "composition": "空",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:接続不能の蝉時雨. Mood:月が低く見えた。\nラムネの泡だけ元気だった。\n空だけ静かだった。",
    "image": "images/memory/104.webp",
    "status": "pending"
  },
  "接続不能の_祭り囃子": {
    "no": "105",
    "memoryId": "M105",
    "word1": "接続不能の",
    "word2": "祭り囃子",
    "title": "接続不能の祭り囃子",
    "poem": "汗が少し乾いた。\n接続不能の祭り囃子を思い出しそうになる。\n太鼓だけ急いでいた。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:接続不能の祭り囃子. Mood:汗が少し乾いた。\n接続不能の祭り囃子を思い出しそうになる。\n太鼓だけ急いでいた。",
    "image": "images/memory/105.webp",
    "status": "pending"
  },
  "接続不能の_帰り道": {
    "no": "106",
    "memoryId": "M106",
    "word1": "接続不能の",
    "word2": "帰り道",
    "title": "接続不能の帰り道",
    "poem": "空はまだ青かった。\nラムネの泡だけ元気だった。\n街灯だけ待っていた。",
    "mood": "Smile",
    "composition": "後ろ姿",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:接続不能の帰り道. Mood:空はまだ青かった。\nラムネの泡だけ元気だった。\n街灯だけ待っていた。",
    "image": "images/memory/106.webp",
    "status": "pending"
  },
  "接続不能の_夜店": {
    "no": "107",
    "memoryId": "M107",
    "word1": "接続不能の",
    "word2": "夜店",
    "title": "接続不能の夜店",
    "poem": "汗が少し乾いた。\n接続不能の夜店を思い出しそうになる。\nお腹だけ急いでいた。",
    "mood": "Serious",
    "composition": "水面",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:接続不能の夜店. Mood:汗が少し乾いた。\n接続不能の夜店を思い出しそうになる。\nお腹だけ急いでいた。",
    "image": "images/memory/107.webp",
    "status": "pending"
  },
  "接続不能の_打ち上げ跡": {
    "no": "108",
    "memoryId": "M108",
    "word1": "接続不能の",
    "word2": "打ち上げ跡",
    "title": "接続不能の打ち上げ跡",
    "poem": "月が低く見えた。\n扇風機に向かって『あー』と言いたくなった。\n静けさだけ広がった。",
    "mood": "Smile",
    "composition": "手元",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:接続不能の打ち上げ跡. Mood:月が低く見えた。\n扇風機に向かって『あー』と言いたくなった。\n静けさだけ広がった。",
    "image": "images/memory/108.webp",
    "status": "pending"
  },
  "404番線の_夏祭り": {
    "no": "109",
    "memoryId": "M109",
    "word1": "404番線の",
    "word2": "夏祭り",
    "title": "404番線の夏祭り",
    "poem": "空はまだ青かった。\n404番線の夏祭りを思い出しそうになる。\n提灯だけが揺れていた。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:404番線の夏祭り. Mood:空はまだ青かった。\n404番線の夏祭りを思い出しそうになる。\n提灯だけが揺れていた。",
    "image": "images/memory/109.webp",
    "status": "pending"
  },
  "404番線の_花火": {
    "no": "110",
    "memoryId": "M110",
    "word1": "404番線の",
    "word2": "花火",
    "title": "404番線の花火",
    "poem": "灯りが水面にほどける。\nビー玉が最後まで出てこない。\n夜だけが残った。",
    "mood": "Smile",
    "composition": "足元",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:404番線の花火. Mood:灯りが水面にほどける。\nビー玉が最後まで出てこない。\n夜だけが残った。",
    "image": "images/memory/110.webp",
    "status": "pending"
  },
  "404番線の_ラムネ": {
    "no": "111",
    "memoryId": "M111",
    "word1": "404番線の",
    "word2": "ラムネ",
    "title": "404番線のラムネ",
    "poem": "夜気がゆっくり近づく。\n404番線のラムネを思い出しそうになる。\n指だけ頑張っていた。",
    "mood": "Serious",
    "composition": "足元",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:404番線のラムネ. Mood:夜気がゆっくり近づく。\n404番線のラムネを思い出しそうになる。\n指だけ頑張っていた。",
    "image": "images/memory/111.webp",
    "status": "pending"
  },
  "404番線の_夕暮れ": {
    "no": "112",
    "memoryId": "M112",
    "word1": "404番線の",
    "word2": "夕暮れ",
    "title": "404番線の夕暮れ",
    "poem": "汗が少し乾いた。\n扇風機に向かって『あー』と言いたくなった。\n影だけ伸びていた。",
    "mood": "Smile",
    "composition": "鳥居",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:404番線の夕暮れ. Mood:汗が少し乾いた。\n扇風機に向かって『あー』と言いたくなった。\n影だけ伸びていた。",
    "image": "images/memory/112.webp",
    "status": "pending"
  },
  "404番線の_鳥居": {
    "no": "113",
    "memoryId": "M113",
    "word1": "404番線の",
    "word2": "鳥居",
    "title": "404番線の鳥居",
    "poem": "月が低く見えた。\n404番線の鳥居を思い出しそうになる。\n境界だけ揺れていた。",
    "mood": "Serious",
    "composition": "手元",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:404番線の鳥居. Mood:月が低く見えた。\n404番線の鳥居を思い出しそうになる。\n境界だけ揺れていた。",
    "image": "images/memory/113.webp",
    "status": "pending"
  },
  "404番線の_灯籠": {
    "no": "114",
    "memoryId": "M114",
    "word1": "404番線の",
    "word2": "灯籠",
    "title": "404番線の灯籠",
    "poem": "風鈴がひとつ鳴った。\nビー玉が最後まで出てこない。\n光だけ流れていた。",
    "mood": "Smile",
    "composition": "足元",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:404番線の灯籠. Mood:風鈴がひとつ鳴った。\nビー玉が最後まで出てこない。\n光だけ流れていた。",
    "image": "images/memory/114.webp",
    "status": "pending"
  },
  "404番線の_河川敷": {
    "no": "115",
    "memoryId": "M115",
    "word1": "404番線の",
    "word2": "河川敷",
    "title": "404番線の河川敷",
    "poem": "月が低く見えた。\n404番線の河川敷を思い出しそうになる。\n水面だけ笑っていた。",
    "mood": "Serious",
    "composition": "手元",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:404番線の河川敷. Mood:月が低く見えた。\n404番線の河川敷を思い出しそうになる。\n水面だけ笑っていた。",
    "image": "images/memory/115.webp",
    "status": "pending"
  },
  "404番線の_蝉時雨": {
    "no": "116",
    "memoryId": "M116",
    "word1": "404番線の",
    "word2": "蝉時雨",
    "title": "404番線の蝉時雨",
    "poem": "風鈴がひとつ鳴った。\n線香花火をまだ信じていた。\n音だけ夏だった。",
    "mood": "Smile",
    "composition": "後ろ姿",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:404番線の蝉時雨. Mood:風鈴がひとつ鳴った。\n線香花火をまだ信じていた。\n音だけ夏だった。",
    "image": "images/memory/116.webp",
    "status": "pending"
  },
  "404番線の_祭り囃子": {
    "no": "117",
    "memoryId": "M117",
    "word1": "404番線の",
    "word2": "祭り囃子",
    "title": "404番線の祭り囃子",
    "poem": "風が少し止んだ。\n404番線の祭り囃子を思い出しそうになる。\n太鼓だけ急いでいた。",
    "mood": "Serious",
    "composition": "手元",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:404番線の祭り囃子. Mood:風が少し止んだ。\n404番線の祭り囃子を思い出しそうになる。\n太鼓だけ急いでいた。",
    "image": "images/memory/117.webp",
    "status": "pending"
  },
  "404番線の_帰り道": {
    "no": "118",
    "memoryId": "M118",
    "word1": "404番線の",
    "word2": "帰り道",
    "title": "404番線の帰り道",
    "poem": "夜気がゆっくり近づく。\nビー玉が最後まで出てこない。\n空だけ知っていた。",
    "mood": "Smile",
    "composition": "空",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:404番線の帰り道. Mood:夜気がゆっくり近づく。\nビー玉が最後まで出てこない。\n空だけ知っていた。",
    "image": "images/memory/118.webp",
    "status": "pending"
  },
  "404番線の_夜店": {
    "no": "119",
    "memoryId": "M119",
    "word1": "404番線の",
    "word2": "夜店",
    "title": "404番線の夜店",
    "poem": "風鈴がひとつ鳴った。\n404番線の夜店を思い出しそうになる。\n匂いだけ笑っていた。",
    "mood": "Serious",
    "composition": "手元",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:404番線の夜店. Mood:風鈴がひとつ鳴った。\n404番線の夜店を思い出しそうになる。\n匂いだけ笑っていた。",
    "image": "images/memory/119.webp",
    "status": "pending"
  },
  "404番線の_打ち上げ跡": {
    "no": "120",
    "memoryId": "M120",
    "word1": "404番線の",
    "word2": "打ち上げ跡",
    "title": "404番線の打ち上げ跡",
    "poem": "空はまだ青かった。\nラムネの泡だけ元気だった。\n火薬の匂いだけ残った。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:404番線の打ち上げ跡. Mood:空はまだ青かった。\nラムネの泡だけ元気だった。\n火薬の匂いだけ残った。",
    "image": "images/memory/120.webp",
    "status": "pending"
  },
  "圏外の_夏祭り": {
    "no": "121",
    "memoryId": "M121",
    "word1": "圏外の",
    "word2": "夏祭り",
    "title": "圏外の夏祭り",
    "poem": "汗が少し乾いた。\n圏外の夏祭りを思い出しそうになる。\n笑い声だけ残った。",
    "mood": "Serious",
    "composition": "手元",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:圏外の夏祭り. Mood:汗が少し乾いた。\n圏外の夏祭りを思い出しそうになる。\n笑い声だけ残った。",
    "image": "images/memory/121.webp",
    "status": "pending"
  },
  "圏外の_花火": {
    "no": "122",
    "memoryId": "M122",
    "word1": "圏外の",
    "word2": "花火",
    "title": "圏外の花火",
    "poem": "風鈴がひとつ鳴った。\nサンダルに小石が入った。\n夜だけが残った。",
    "mood": "Smile",
    "composition": "手元",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:圏外の花火. Mood:風鈴がひとつ鳴った。\nサンダルに小石が入った。\n夜だけが残った。",
    "image": "images/memory/122.webp",
    "status": "pending"
  },
  "圏外の_ラムネ": {
    "no": "123",
    "memoryId": "M123",
    "word1": "圏外の",
    "word2": "ラムネ",
    "title": "圏外のラムネ",
    "poem": "風が少し止んだ。\n圏外のラムネを思い出しそうになる。\nビー玉だけ帰らなかった。",
    "mood": "Serious",
    "composition": "鳥居",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:圏外のラムネ. Mood:風が少し止んだ。\n圏外のラムネを思い出しそうになる。\nビー玉だけ帰らなかった。",
    "image": "images/memory/123.webp",
    "status": "pending"
  },
  "圏外の_夕暮れ": {
    "no": "124",
    "memoryId": "M124",
    "word1": "圏外の",
    "word2": "夕暮れ",
    "title": "圏外の夕暮れ",
    "poem": "汗が少し乾いた。\n線香花火をまだ信じていた。\n風だけ知っていた。",
    "mood": "Smile",
    "composition": "手元",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:圏外の夕暮れ. Mood:汗が少し乾いた。\n線香花火をまだ信じていた。\n風だけ知っていた。",
    "image": "images/memory/124.webp",
    "status": "pending"
  },
  "圏外の_鳥居": {
    "no": "125",
    "memoryId": "M125",
    "word1": "圏外の",
    "word2": "鳥居",
    "title": "圏外の鳥居",
    "poem": "月が低く見えた。\n圏外の鳥居を思い出しそうになる。\n境界だけ揺れていた。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:圏外の鳥居. Mood:月が低く見えた。\n圏外の鳥居を思い出しそうになる。\n境界だけ揺れていた。",
    "image": "images/memory/125.webp",
    "status": "pending"
  },
  "圏外の_灯籠": {
    "no": "126",
    "memoryId": "M126",
    "word1": "圏外の",
    "word2": "灯籠",
    "title": "圏外の灯籠",
    "poem": "夜気がゆっくり近づく。\n線香花火をまだ信じていた。\n光だけ流れていた。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:圏外の灯籠. Mood:夜気がゆっくり近づく。\n線香花火をまだ信じていた。\n光だけ流れていた。",
    "image": "images/memory/126.webp",
    "status": "pending"
  },
  "圏外の_河川敷": {
    "no": "127",
    "memoryId": "M127",
    "word1": "圏外の",
    "word2": "河川敷",
    "title": "圏外の河川敷",
    "poem": "夜気がゆっくり近づく。\n圏外の河川敷を思い出しそうになる。\n足音だけ続いていた。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:圏外の河川敷. Mood:夜気がゆっくり近づく。\n圏外の河川敷を思い出しそうになる。\n足音だけ続いていた。",
    "image": "images/memory/127.webp",
    "status": "pending"
  },
  "圏外の_蝉時雨": {
    "no": "128",
    "memoryId": "M128",
    "word1": "圏外の",
    "word2": "蝉時雨",
    "title": "圏外の蝉時雨",
    "poem": "ノイズが静かに混ざる。\nビー玉が最後まで出てこない。\n木陰だけ涼しかった。",
    "mood": "Smile",
    "composition": "空",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:圏外の蝉時雨. Mood:ノイズが静かに混ざる。\nビー玉が最後まで出てこない。\n木陰だけ涼しかった。",
    "image": "images/memory/128.webp",
    "status": "pending"
  },
  "圏外の_祭り囃子": {
    "no": "129",
    "memoryId": "M129",
    "word1": "圏外の",
    "word2": "祭り囃子",
    "title": "圏外の祭り囃子",
    "poem": "夜気がゆっくり近づく。\n圏外の祭り囃子を思い出しそうになる。\n夜だけ踊っていた。",
    "mood": "Serious",
    "composition": "足元",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:圏外の祭り囃子. Mood:夜気がゆっくり近づく。\n圏外の祭り囃子を思い出しそうになる。\n夜だけ踊っていた。",
    "image": "images/memory/129.webp",
    "status": "pending"
  },
  "圏外の_帰り道": {
    "no": "130",
    "memoryId": "M130",
    "word1": "圏外の",
    "word2": "帰り道",
    "title": "圏外の帰り道",
    "poem": "汗が少し乾いた。\nサンダルに小石が入った。\n空だけ知っていた。",
    "mood": "Smile",
    "composition": "空",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:圏外の帰り道. Mood:汗が少し乾いた。\nサンダルに小石が入った。\n空だけ知っていた。",
    "image": "images/memory/130.webp",
    "status": "pending"
  },
  "圏外の_夜店": {
    "no": "131",
    "memoryId": "M131",
    "word1": "圏外の",
    "word2": "夜店",
    "title": "圏外の夜店",
    "poem": "汗が少し乾いた。\n圏外の夜店を思い出しそうになる。\n財布だけ静かだった。",
    "mood": "Serious",
    "composition": "水面",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:圏外の夜店. Mood:汗が少し乾いた。\n圏外の夜店を思い出しそうになる。\n財布だけ静かだった。",
    "image": "images/memory/131.webp",
    "status": "pending"
  },
  "圏外の_打ち上げ跡": {
    "no": "132",
    "memoryId": "M132",
    "word1": "圏外の",
    "word2": "打ち上げ跡",
    "title": "圏外の打ち上げ跡",
    "poem": "風鈴がひとつ鳴った。\nビー玉が最後まで出てこない。\n火薬の匂いだけ残った。",
    "mood": "Smile",
    "composition": "後ろ姿",
    "lighting": "青白い光",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:圏外の打ち上げ跡. Mood:風鈴がひとつ鳴った。\nビー玉が最後まで出てこない。\n火薬の匂いだけ残った。",
    "image": "images/memory/132.webp",
    "status": "pending"
  },
  "ノイズ混じりの_夏祭り": {
    "no": "133",
    "memoryId": "M133",
    "word1": "ノイズ混じりの",
    "word2": "夏祭り",
    "title": "ノイズ混じりの夏祭り",
    "poem": "ノイズが静かに混ざる。\nノイズ混じりの夏祭りを思い出しそうになる。\n提灯だけが揺れていた。",
    "mood": "Serious",
    "composition": "空",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:ノイズ混じりの夏祭り. Mood:ノイズが静かに混ざる。\nノイズ混じりの夏祭りを思い出しそうになる。\n提灯だけが揺れていた。",
    "image": "images/memory/133.webp",
    "status": "pending"
  },
  "ノイズ混じりの_花火": {
    "no": "134",
    "memoryId": "M134",
    "word1": "ノイズ混じりの",
    "word2": "花火",
    "title": "ノイズ混じりの花火",
    "poem": "月が低く見えた。\nラムネの泡だけ元気だった。\n夜だけが残った。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:ノイズ混じりの花火. Mood:月が低く見えた。\nラムネの泡だけ元気だった。\n夜だけが残った。",
    "image": "images/memory/134.webp",
    "status": "pending"
  },
  "ノイズ混じりの_ラムネ": {
    "no": "135",
    "memoryId": "M135",
    "word1": "ノイズ混じりの",
    "word2": "ラムネ",
    "title": "ノイズ混じりのラムネ",
    "poem": "月が低く見えた。\nノイズ混じりのラムネを思い出しそうになる。\n指だけ頑張っていた。",
    "mood": "Serious",
    "composition": "後ろ姿",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:ノイズ混じりのラムネ. Mood:月が低く見えた。\nノイズ混じりのラムネを思い出しそうになる。\n指だけ頑張っていた。",
    "image": "images/memory/135.webp",
    "status": "pending"
  },
  "ノイズ混じりの_夕暮れ": {
    "no": "136",
    "memoryId": "M136",
    "word1": "ノイズ混じりの",
    "word2": "夕暮れ",
    "title": "ノイズ混じりの夕暮れ",
    "poem": "風鈴がひとつ鳴った。\n扇風機に向かって『あー』と言いたくなった。\n風だけ知っていた。",
    "mood": "Smile",
    "composition": "鳥居",
    "lighting": "月明かり",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:ノイズ混じりの夕暮れ. Mood:風鈴がひとつ鳴った。\n扇風機に向かって『あー』と言いたくなった。\n風だけ知っていた。",
    "image": "images/memory/136.webp",
    "status": "pending"
  },
  "ノイズ混じりの_鳥居": {
    "no": "137",
    "memoryId": "M137",
    "word1": "ノイズ混じりの",
    "word2": "鳥居",
    "title": "ノイズ混じりの鳥居",
    "poem": "夜気がゆっくり近づく。\nノイズ混じりの鳥居を思い出しそうになる。\n境界だけ揺れていた。",
    "mood": "Serious",
    "composition": "横顔",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:ノイズ混じりの鳥居. Mood:夜気がゆっくり近づく。\nノイズ混じりの鳥居を思い出しそうになる。\n境界だけ揺れていた。",
    "image": "images/memory/137.webp",
    "status": "pending"
  },
  "ノイズ混じりの_灯籠": {
    "no": "138",
    "memoryId": "M138",
    "word1": "ノイズ混じりの",
    "word2": "灯籠",
    "title": "ノイズ混じりの灯籠",
    "poem": "夜気がゆっくり近づく。\n扇風機に向かって『あー』と言いたくなった。\n光だけ流れていた。",
    "mood": "Smile",
    "composition": "横顔",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:ノイズ混じりの灯籠. Mood:夜気がゆっくり近づく。\n扇風機に向かって『あー』と言いたくなった。\n光だけ流れていた。",
    "image": "images/memory/138.webp",
    "status": "pending"
  },
  "ノイズ混じりの_河川敷": {
    "no": "139",
    "memoryId": "M139",
    "word1": "ノイズ混じりの",
    "word2": "河川敷",
    "title": "ノイズ混じりの河川敷",
    "poem": "夜気がゆっくり近づく。\nノイズ混じりの河川敷を思い出しそうになる。\n足音だけ続いていた。",
    "mood": "Serious",
    "composition": "手元",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:ノイズ混じりの河川敷. Mood:夜気がゆっくり近づく。\nノイズ混じりの河川敷を思い出しそうになる。\n足音だけ続いていた。",
    "image": "images/memory/139.webp",
    "status": "pending"
  },
  "ノイズ混じりの_蝉時雨": {
    "no": "140",
    "memoryId": "M140",
    "word1": "ノイズ混じりの",
    "word2": "蝉時雨",
    "title": "ノイズ混じりの蝉時雨",
    "poem": "夜気がゆっくり近づく。\n扇風機に向かって『あー』と言いたくなった。\n空だけ静かだった。",
    "mood": "Smile",
    "composition": "足元",
    "lighting": "花火",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:ノイズ混じりの蝉時雨. Mood:夜気がゆっくり近づく。\n扇風機に向かって『あー』と言いたくなった。\n空だけ静かだった。",
    "image": "images/memory/140.webp",
    "status": "pending"
  },
  "ノイズ混じりの_祭り囃子": {
    "no": "141",
    "memoryId": "M141",
    "word1": "ノイズ混じりの",
    "word2": "祭り囃子",
    "title": "ノイズ混じりの祭り囃子",
    "poem": "空はまだ青かった。\nノイズ混じりの祭り囃子を思い出しそうになる。\n夜だけ踊っていた。",
    "mood": "Serious",
    "composition": "足元",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:ノイズ混じりの祭り囃子. Mood:空はまだ青かった。\nノイズ混じりの祭り囃子を思い出しそうになる。\n夜だけ踊っていた。",
    "image": "images/memory/141.webp",
    "status": "pending"
  },
  "ノイズ混じりの_帰り道": {
    "no": "142",
    "memoryId": "M142",
    "word1": "ノイズ混じりの",
    "word2": "帰り道",
    "title": "ノイズ混じりの帰り道",
    "poem": "風鈴がひとつ鳴った。\nビー玉が最後まで出てこない。\n街灯だけ待っていた。",
    "mood": "Smile",
    "composition": "水面",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:ノイズ混じりの帰り道. Mood:風鈴がひとつ鳴った。\nビー玉が最後まで出てこない。\n街灯だけ待っていた。",
    "image": "images/memory/142.webp",
    "status": "pending"
  },
  "ノイズ混じりの_夜店": {
    "no": "143",
    "memoryId": "M143",
    "word1": "ノイズ混じりの",
    "word2": "夜店",
    "title": "ノイズ混じりの夜店",
    "poem": "灯りが水面にほどける。\nノイズ混じりの夜店を思い出しそうになる。\nお腹だけ急いでいた。",
    "mood": "Serious",
    "composition": "手元",
    "lighting": "灯籠",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:ノイズ混じりの夜店. Mood:灯りが水面にほどける。\nノイズ混じりの夜店を思い出しそうになる。\nお腹だけ急いでいた。",
    "image": "images/memory/143.webp",
    "status": "pending"
  },
  "ノイズ混じりの_打ち上げ跡": {
    "no": "144",
    "memoryId": "M144",
    "word1": "ノイズ混じりの",
    "word2": "打ち上げ跡",
    "title": "ノイズ混じりの打ち上げ跡",
    "poem": "空はまだ青かった。\nサンダルに小石が入った。\n火薬の匂いだけ残った。",
    "mood": "Smile",
    "composition": "後ろ姿",
    "lighting": "夕暮れ",
    "prompt": "Dreamlike nostalgic Japanese summer festival at night, emotional anime illustration, subtle VHS noise, soft blue-white glow, 9:16, no text. Theme:ノイズ混じりの打ち上げ跡. Mood:空はまだ青かった。\nサンダルに小石が入った。\n火薬の匂いだけ残った。",
    "image": "images/memory/144.webp",
    "status": "pending"
  }
};
